#!/bin/bash
set -e

# Exit if this is the scripts dir
[[ scripts != ${PWD##*/} ]] || exit 0

s3d-format

# If a local init script exists we run it
if [ -f ./s3d-init ]; then
  ./s3d-init
fi

# If main.tf exits, we also init by running terrafom validate
if [ -f main.tf ]; then
  terraform init
fi

# If main.go, we run go tidy
if [ -f main.go ]; then
  go mod tidy
fi

# If package.json, we run npm
if [ -f package.json ]; then
  npm install
fi
