#!/bin/bash
set -e

# Exit if this is the scripts dir
[[ scripts != ${PWD##*/} ]] || exit 0

s3d-format

# If a local init script exists we run it
if [ -f ./s3d-init ]; then
  ./s3d-init
fi

# If main.tf exits, we also init by running terrafom validate
if [ -f main.tf ]; then
	log="$HOME/.s3d/logs/$(uuidgen | cut -c 1-8).log"
  { { 
		terraform get -update && terraform init; 
	} > $log 2>&1; } || {
		cat $log >&2
		exit -1
	}
fi

# If main.go, we run go tidy
if [ -f main.go ]; then
  go mod tidy
fi

# If package.json, we run npm
if [ -f package.json ]; then
  npm install
fi
