#!/bin/bash
set -e

# Run local flow
if [[ 's3d-scripts' != "${PWD##*/}" ]]; then
  if [ -e ./s3d-flow ]; then
    ./s3d-flow
  fi
fi

# Commit, tag and push
s3d-flow-commit
s3d-flow-tag
git push ssh HEAD:next

# Checkout a "Detatched" head
git checkout 'HEAD~0'
