#!/bin/bash

set -e

rm -rf .terraform*

terraform init

terraform providers lock \
  -platform=windows_amd64 \
  -platform=darwin_arm64 \
  -platform=darwin_amd64 \
  -platform=linux_amd64 \
  -platform=linux_arm64
