#!/bin/bash

v="$(s3d-current-release | jq -r '.latest')"

if [[ "$v" != $(git log -n 1 --format='%s') ]]; then
  git add -A
  git commit --allow-empty -m "$v"
fi

git tag -m release "$v"
git push ssh "$v"
