#!/bin/bash
set -e

# We need all submodule flows to be done first
git submodule foreach s3d-flow

# If the status is clean we are done
if [[ 0 = $(git status --porcelain  | wc -l) ]]; then
	echo -e 'FLOW: Status is clean' >&2
	exit 0
fi

flow_branch=$1
flow_branch=${flow_branch:-next}

v=$(s3d-flow-json | jq -r .latest)
v2=$(s3d-flow-json | jq -r .release)
if [[ $v == $v2 ]]; then
  s3d-flow-check
  if [[ $flow_branch == 'ssh/main' ]]; then
    flow_branch=main
  else
    echo 'ERROR: Flow not started' >&2
    exit 1
  fi
fi
 
# Commit, tag and push
s3d-flow-commit
s3d-flow-tag
git push ssh HEAD:$flow_branch

# Checkout a "Detatched" head
git checkout -q HEAD~0

