#!/bin/bash
set -e

v=$(s3d-flow-json | jq -r .latest)
v2=$(s3d-flow-json | jq -r .release)
if [[ "$v" == "$v2" ]]; then
  echo 'Already finished'
else
  v_=$(echo $v | sed 's/\./\\\./')
  v2_=$(echo $v2 | sed 's/\./\\\./')
  sed -i -e 's/\['"$v_"'\]/\['"$v2_"'\]/' CHANGES.md
  s3d-flow-reset
  s3d-flow main
fi
