#!/bin/bash

ver=$(s3d-changes | jq -r '.latest')
verSed=$(echo $ver | sed 's/\./\\\./')
block=$(sed -e '/Next/,$d' < CHANGES.md | sed -n -e "/$verSed/,\$p")
block=$(echo "$block" | grep -v -E '^##')
done=$(echo "$block" | grep -v -E '^- \*\*TODO\*\*' | wc -l)
items=$(echo "$block" | grep -E '^-' | wc -l)
commit=$"$ver Changes; $done of $items completed"
commit="$commit"$'\n\n';
commit="$commit$block"
git add -A
git commit -m "$commit"
