#!/bin/bash
set -e

if [ -e ./s3d-finish ]; then
  ./s3d-finish
fi

if [ -e ./main.tf ]; then
  "$(dirname "$0")/hooks/s3d-finish-tf"
fi

s3d-flow-check

v=$(s3d-flow-json | jq -r .latest)
v2=$(s3d-flow-json | jq -r .release)
if [[ "$v" == "$v2" ]]; then
  echo 'Already finished'
else
  v_=$(echo $v | sed 's/\./\\\./')
  v2_=$(echo $v2 | sed 's/\./\\\./')
  sed -i -e 's/\['"$v_"'\]/\['"$v2_"'\]/' CHANGES.md
  s3d-flow-reset
  s3d-flow ssh/main
fi
