#!/bin/bash
set -e

# Exit if this is the scripts dir
[[ scripts != ${PWD##*/} ]] || exit 0

s3d-init

[ ! -f ./s3d-test ] || ./s3d-test

# If main.tf exits we also test by running terrafom validate
if [ -f main.tf ]; then
  terraform validate
fi
